---
interactive_users:
  # Tom Hampson
  - username: dsc49661
    sudoer: true
    ssh_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCe3et6Rw6b3v8WzERRS0DE1cm33Te3WcUOgzU5xV8tZd0YgTMy1VENG4daZNjlY4ZJ+JMRIehqyOWXEbnJ5d0phdoM6qGj+Wp4WGzvqRHzDcfZC+vAZPsLEwGlcCwLUDihgwpiWePIYVUUuWD5uIEVEPA7mLYvVRwnE6sipGimWXkEpNlRlJZht17w7vCkqFkYx9ULrdXfo29AWkVHqkJcVgBqkg9kglxyerIwy0BXahnDW56WSfPK47ZgcktI7+qu2tu6ZoyyUZZ/rZze3BoQ9f6hJkp0jCN33MPAHZxTL9nkYgG6sWO2TzgM49z6zd2av3pN6NxYA6z5sH9yagMd5L6dSLmMjodfCBdrtyaAgXXhySgq71xtzYUgRVxLLJ/MnVb5vqiExUxAppxYa4JXkeXikTNGXjMPgcs6Bo55i/T7rvjjAQAobK7q6ppYUUBu0V7TM/72P/hC44NChci1FC+6rQcuEJ8I1824pcngdRE432gmb3iBQN7XefUI74s= CLRC+dsc49661@NDLT1577"
