- name: Fetch GitHub Actions runner registration token
  uri:
    url: "https://api.github.com/repos/{{ organization }}/{{ repository }}/actions/runners/registration-token"
    method: POST
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ github_token }}"
      X-GitHub-Api-Version: "2022-11-28"
    return_content: yes
    status_code: 201
  register: runner_token
  delegate_to: localhost

- name: Deploy dockerized GitHub runner
  community.docker.docker_container:
    name: "{{ runner_name }}"
    image: "ghcr.io/{{ organization }}/github-runner-win:0.1"
    detach: yes
    recreate: yes
    pull: yes
    env:
      RUNNER_NAME: "{{ runner_name }}"
      ORGANIZATION: "{{ organization }}"
      REPOSITORY: "{{ repository }}"
      REG_TOKEN: "{{ runner_token.json.token }}"
