- name: Deploy dockerized Jenkins agent
  community.docker.docker_container:
    name: "{{ agent_name }}"
    image: ghcr.io/mantidproject/jenkins-node-centos7-slim:latest
    detach: yes
    init: yes
    network_mode: host
    recreate: yes
    pull: yes
    shm_size: 512M
    volumes:
      - "{{ agent_name }}:/jenkins_workdir"
      - "{{ agent_name }}_ccache:/ccache"
      - "{{ agent_name }}_external_data:/mantid_data"
    env:
      JENKINS_AGENT_NAME: "{{ agent_name }}"
      JENKINS_SECRET: "{{ agent_secret }}"
      JENKINS_URL: "{{ jenkins_url }}"
    when: "'staging' not in ansible_run_tags"

- name: Deploy dockerized Jenkins agent - staging
  community.docker.docker_container:
    name: "{{ agent_name }}"
    image: ghcr.io/mantidproject/jenkins-node-centos7-slim:latest
    detach: yes
    init: yes
    network_mode: host
    recreate: yes
    pull: yes
    shm_size: 512M
    volumes:
      - "{{ agent_name }}:/jenkins_workdir"
      - "{{ agent_name }}_ccache:/ccache"
      - "{{ agent_name }}_external_data:/mantid_data"
    env:
      JENKINS_AGENT_NAME: "{{ agent_name }}"
      JENKINS_SECRET: "{{ agent_secret }}"
      JENKINS_DIRECT_CONNECTION: "{{ jenkins_url }}:37899"
      JENKINS_INSTANCE_IDENTITY: "{{ jenkins_identity }}"
    tags:
      - staging
