FROM centos:7

ARG PACKAGE
ADD ${PACKAGE} /tmp/mantid.rpm

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum copr enable -y mantid/mantid && \
    yum localinstall -y /tmp/mantid.rpm && \
    rm -rf /tmp/*

# Add Mantid to PATH
ENV PATH=/opt/mantidnightly/bin/:${PATH}
