FROM centos:7

ARG MANTID_VERSION

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y yum-plugin-copr wget && \
    yum copr enable -y mantid/mantid && \
    wget -O /tmp/mantid.rpm https://github.com/mantidproject/mantid/releases/download/v${MANTID_VERSION}/mantid-${MANTID_VERSION}-1.el7.x86_64.rpm && \
    yum localinstall -y /tmp/mantid.rpm && \
    rm -rf /tmp/*

# Add Mantid to PATH
ENV PATH=/opt/Mantid/bin/:${PATH}
