FROM ubuntu:16.04

ARG MANTID_VERSION

RUN apt-get update && \
    apt-get install -y software-properties-common wget gdebi && \
    wget -O - http://apt.isis.rl.ac.uk/2E10C193726B7213.asc | apt-key add - && \
    apt-add-repository -y "deb [arch=amd64] http://apt.isis.rl.ac.uk $(lsb_release -c | cut -f 2) main" && \
    apt-add-repository -y ppa:mantid/mantid && \
    apt-get update && \
    wget -O /tmp/mantid.deb https://github.com/mantidproject/mantid/releases/download/v${MANTID_VERSION}/mantid_${MANTID_VERSION}-0ubuntu1_xenial1_amd64.deb && \
    gdebi --non-interactive /tmp/mantid.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Add Mantid to PATH
ENV PATH=/opt/Mantid/bin/:${PATH}
