- name: Create a directory to hold the mirror of the external data.
  ansible.builtin.file:
    path: /mantid_data/MD5/
    state: directory
    mode: '0755'

- name: Check if machine has SSH access to the ISIS data store.
  ansible.builtin.command: ssh -o BatchMode=True mkq48465@{{ data_server_hostname }} 'echo success'
  register: connected
  ignore_errors: True

- name: Exchange SSH keys with linode so we can access the data.
  import_tasks: exchange-keys.yml
  when: connected.stdout != "success"

- name: Mirror the external data from the main server in a volume (this may take a while).
  ansible.builtin.command: "rsync -az --perms -o -g mkq48465@{{ data_server_hostname }}:/external-data/MD5/ /mantid_data/MD5 -v"

- name: Copy the data update script onto the mirror machine.
  ansible.builtin.copy:
    src: ./update-external-data.sh
    dest: /external-data/update-external-data.sh
    mode: '0755'

- name: Create a crontab job that runs periodically to keep the data up to date.
  ansible.builtin.cron:
    name: Update external data
    minute: "*/5"
    job: /external-data/update-external-data.sh {{ data_server_hostname }} >> /external-data/update-log.txt 2>&1
