---
# Get homebrew ready for installing other dependencies.

- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Upgrade openssl.
  community.general.homebrew:
    name: openssl@3
    state: latest

- name: Remove old openssl versions.
  community.general.homebrew:
    name: openssl@1.1
    state: absent

- name: Upgrade homebrew.
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Make sure homebrew bin is in the path.
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root
