---
# Get homebrew ready for installing other dependencies.

- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Make sure homebrew bin is in the path.
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root
