FROM centos:7

# Add Mantid repository and install developer package and GCC 7
ARG DEV_PACKAGE_VERSION
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y yum-plugin-copr centos-release-scl && \
    yum copr enable -y mantid/mantid && \
    yum install -y mantid-developer-${DEV_PACKAGE_VERSION} devtoolset-7-gcc-c++

# Install static analysis dependencies
RUN pip install flake8==2.5.4 pep8==1.6.2 pyflakes==1.3.0 mccabe==0.6.1

# Create source, build and external data directories
RUN mkdir -p /mantid_src && \
    mkdir -p /mantid_build && \
    mkdir -p /mantid_data

# Allow mounting source, build and data directories
VOLUME ["/mantid_src", "/mantid_build", "/mantid_data"]

# Set default working directory to build directory
WORKDIR /mantid_build
