- name: Deploy Docker-based GitHub runner for Mantid builds
  hosts: all
  vars:
    package_updates_reboot: true
    pip_install_packages:
      - name: docker

  roles:
    - role: dannixon.system.package_updates
      tags: "initial-setup"
    - role: dannixon.system.interactive_users
      tags: "initial-setup"      
    - role: geerlingguy.pip
      become: yes
      tags: "initial-setup"      
    - role: geerlingguy.docker
      become: yes
      tags: "initial-setup"      
    - role: runner
      become: yes
      tags: "runner"
