- name: Playbook to clean jenkins agents by removing workspaces.
  hosts: all

  # Tags available: pr, nightly, package, docs
  tasks:
  - name: Collect workspace sizes
    community.docker.docker_container_exec:
      container: "{{ agent_name }}"
      command: bash -l -c "du -sh * | column -t"
      chdir: "/jenkins_workdir/workspace"
    register: du_result
    become: yes
    tags: [always]

  - name: Display workspace sizes
    debug:
      msg: "{{ du_result.stdout_lines }}"
    tags: [always]

  - name: Remove PR directories
    community.docker.docker_container_exec:
      container: "{{ agent_name }}"
      command: bash -l -c "rm -rf pull_requests*"
      chdir: "/jenkins_workdir/workspace"
    become: yes
    tags: [never, pr]

  - name: Remove Nightly directories
    community.docker.docker_container_exec:
      container: "{{ agent_name }}"
      command: bash -l -c "rm -rf *_nightly_deployment*"
      chdir: "/jenkins_workdir/workspace"
    become: yes
    tags: [never, nightly]

  - name: Remove Packages from Branch directories
    community.docker.docker_container_exec:
      container: "{{ agent_name }}"
      command: bash -l -c "rm -rf build_packages_from_branch*"
      chdir: "/jenkins_workdir/workspace"
    become: yes
    tags: [never, package]

  - name: Remove Docs Build directories
    community.docker.docker_container_exec:
      container: "{{ agent_name }}"
      command: bash -l -c "rm -rf build_and_publish_docs*"
      chdir: "/jenkins_workdir/workspace"
    become: yes
    tags: [never, docs]
