- name: Deploy Docker-based Jenkins agent for Mantid builds
  hosts: all
  vars:
    deploy_type: production
    jenkins_url: https://builds.mantidproject.org
    data_server_hostname: 172.16.114.127
    pip_install_packages:
      - name: docker

  roles:
    - role: setup
      tags: "initial-setup"
    - role: interactive_users
      tags: "initial-setup"
    - role: geerlingguy.pip
      become: yes
      tags: "initial-setup"
    - role: geerlingguy.docker
      become: yes
      tags: "initial-setup"
    - role: mirror-data  # ONLY WORKS FOR ISIS NODES
      become: yes
      tags: ["mirror", never]
    - role: agent
      become: yes
      tags: "agent"
