- name: Deploy Docker-based Jenkins agent for Mantid builds
  hosts: all
  vars:
    deploy_type: production
    jenkins_url: https://builds.mantidproject.org
    pip_install_packages:
      - name: docker

  roles:
    - role: setup
      tags: "initial-setup"
    - role: interactive_users
      tags: "initial-setup"      
    - role: geerlingguy.pip
      become: yes
      tags: "initial-setup"      
    - role: geerlingguy.docker
      become: yes
      tags: "initial-setup"      
    - role: agent
      become: yes
      tags: "agent"
