#!/bin/bash

#
# retrieve and equate semantic version with latest tag
#

# initial URL for first page of API response
next_url="https://hub.docker.com/v2/repositories/library/almalinux/tags/?page=1&page_size=100"

paginated_results=()

while [ -n "${next_url}" ]; do
  # fetch data and extract next_url and paginated tags list
  response=$(curl -s "${next_url}")

  # use jq to extract the next URL and append tags list
  next_url=$(echo "${response}" | jq -r '.next')

  # append items from current page to the paginated_results
  # jq -c means flatten JSON output into a single line
  items=$(echo "${response}" | jq -c '.results')

  # append the current page's items to paginated results array
  while IFS= read -r item; do
    paginated_results+=("${item}")
  done <<< "${items}"
done

#
# Output the combined array of all items as a single JSON object, then flatten and filter
# to find the semantic version (x.y) tag that shares the same digest as the latest tag
#
printf 'semver_tag=%s\n' "${paginated_results[@]}" | jq -r '.
  | flatten | map(del(.images)) | group_by(.digest) | .[]
  | select(.[].name == "latest") | .[]
  | select(.name | match("^\\d+.\\d+$"))
'
