#!/bin/bash

#
# Retrieve all equivalent tags sharing a common image digest
# i.e. Find all sibling tags
#
# example:
# 
# ./utils/equate_tag_siblings "docker.io/library/almalinux:latest"
#
# where:
#   "docker.io" is the registry host
#   "library/almalinux" is the image
#   "latest" is the tag
#

_docker_io() {

  local repository="${1%%*/}"
  local image="${1##/*}"
  local tag_converse="${2}"

  # initial URL for first page of API response
  next_url="https://hub.docker.com/v2/repositories/${image}/tags/?page=1&page_size=100"

  paginated_results=()

  while [ -n "${next_url}" ]; do
    # fetch data and extract next_url and paginated tags list
    response=$(curl -s "${next_url}")

    # use jq to extract the next URL and append tags list
    next_url=$(echo "${response}" | jq -r '.next')

    # append items from current page to the paginated_results
    # jq -c means flatten JSON output into a single line
    items=$(echo "${response}" | jq -c '.results')

    # append the current page's items to paginated results array
    while IFS= read -r item; do
      paginated_results+=("${item}")
    done <<< "${items}"
  done

  #
  # Output the combined array of all items as a single JSON object, then flatten and filter
  # to find the semantic version (x.y) tag that shares the same digest as the latest tag
  #
  printf '%s\n' "${paginated_results[@]}" \
    | jq -r --arg tag_converse "${tag_converse}" '.
      | flatten | map(del(.images)) | group_by(.digest) | .[]
      | select(.[].name == $tag_converse) | .[]
      | select(.name != $tag_converse) | .name
    '
  #
  #
  # https://stackoverflow.com/questions/28320134/how-can-i-list-all-tags-for-a-docker-image-on-a-remote-registry
  #
}


_ghcr_io() {

  local repository="${1%%/*}"
  local image="${1##*/}"
  local tag_converse="${2}"

  local access_token="${GITHUB_TOKEN}"
  local bearer_token=""

  if [[ -n "${access_token}" ]]; then
    read -r bearer_token <<< $(
      curl \
          -u "x-access-token:${access_token}" \
          -s \
        "https://ghcr.io/token?service=ghcr.io&scope=repository:${repository}/${image}:pull" \
      | jq -r '.token'
    )
  fi

  for tag in $(
        curl \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            -H "Authorization: Bearer ${bearer_token:-null}" \
            -s \
          "https://ghcr.io/v2/${repository}/${image}/tags/list" \
        | jq -r '.tags[]'
      )
  do
    #
    # TODO: retrieve manifest digest
    # https://gist.github.com/eggplants/a046346571de66656f4d4d34de69fdd0?permalink_comment_id=5319436#gistcomment-5319436
    #
    # GHCR only seems to respond to the digest of each artifact, 
    # but DockerHub can give me the manifest digest of the repo without a token.
    #
      curl \
          -H "Accept: application/vnd.oci.image.manifest.v1+json" \
          -H "Authorization: Bearer ${bearer_token:-null}" \
          -s \
        "https://ghcr.io/v2/${repository}/${image}/manifests/${tag}" \
      | jq -r --arg tag "${tag}" '{tag: $tag, digest: .config.digest}'
  done \
    | jq -r --arg tag_converse "${tag_converse}" -s '.
      | group_by(.digest) | .[]
      | select(.[].tag == $tag_converse) | .[]
      | select(.tag != $tag_converse) | .tag
    '
}

registry="${1%%/*}"
repository="${1#*/}"
repository="${repository%%:*}"
tag="${1##*:}"

set -x
"_${registry//./_}" "${repository}" "${tag}"

#
# invoke the corresponding function based on the registry hostname
#
# i.e.
#   "ghcr.io/mantidproject/mantid-development-alma:9.6"  is passed to _ghcr_io()
#   "docker.io/library/alpine"                           is passed to _docker_io()
#
