#!/bin/bash

#
# Retrieve and equate semantic version with given tag
#
# example:
# 
# ./utils/equate_tag_semver "docker.io/library/almalinux:latest"
#
# where:
#   "docker.io" is the registry host
#   "library/almalinux" is the image
#   "latest" is the tag
#

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd -P )" ; readonly "${_%%=*}"

cd ${script_dir}

#
# Invoke equate_tag and then filter for semantic version tag
#
./equate_tag "$@"

