#!/bin/bash

#
# retrieve and equate semantic version with given tag
#
#
# example:
# 
# ./utils/equate_tag_semver "library/almalinux:latest"
#
# where "library/almalinux" is the image and "latest" is the tag
#

image=${1%%:*}
tag=${1##*:}

# initial URL for first page of API response
next_url="https://hub.docker.com/v2/repositories/${image}/tags/?page=1&page_size=100"

paginated_results=()

while [ -n "${next_url}" ]; do
  # fetch data and extract next_url and paginated tags list
  response=$(curl -s "${next_url}")

  # use jq to extract the next URL and append tags list
  next_url=$(echo "${response}" | jq -r '.next')

  # append items from current page to the paginated_results
  # jq -c means flatten JSON output into a single line
  items=$(echo "${response}" | jq -c '.results')

  # append the current page's items to paginated results array
  while IFS= read -r item; do
    paginated_results+=("${item}")
  done <<< "${items}"
done

#
# Output the combined array of all items as a single JSON object, then flatten and filter
# to find the semantic version (x.y) tag that shares the same digest as the latest tag
#
printf '%s\n' "${paginated_results[@]}" \
  | jq -r --arg tag "${tag}" '.
    | flatten | map(del(.images)) | group_by(.digest) | .[]
    | select(.[].name == $tag) | .[]
    | select(.name | match("^\\d+.\\d+$")) | .name
  '

#
#
# https://stackoverflow.com/questions/28320134/how-can-i-list-all-tags-for-a-docker-image-on-a-remote-registry
#
