# Set up Java 11 Installation.

- name: Install Java 11.
  community.general.homebrew:
    name: java11
    state: present

- name: Symlink Java 11.
  shell: ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
  become: true
  become_user: root

- name: Ensure that the java install has been added to the path.
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
    create: true
