---
# Deploy Jenkins agent on macOS

# Set up the environment

- name: Add user to sudoers on new macs.
  shell: /Applications/Privileges.app/Contents/Resources/PrivilegesCLI --add
  ignore_errors: true  # Not all the macs have these, so don't panic if it fails.
    
# Install Requirements

- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Make sure homebrew bin is in the path.
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root

- name: Install git.
  community.general.homebrew:
    name: git
    state: latest

- name: Install Java 11.
  community.general.homebrew:
    name: java11
    state: present

# Configure macOS Settings.

- name: Disable screensaver.
  shell: defaults write com.apple.screensaver idleTime 0

- name: Disable saved application states to avoid dialog.
  shell: defaults write org.python.python NSQuitAlwaysKeepsWindows -bool false

# Test and start the agent. Note: Connection will only begin consistently every 5th minute if changes are made.

- name: Download jenkins slave script.
  shell: curl -o $HOME/jenkins-slave.sh https://raw.githubusercontent.com/mantidproject/mantid/main/buildconfig/Jenkins/jenkins-slave.sh

- name: Make the slave script executable.
  shell: chmod 777 $HOME/jenkins-slave.sh

- name: Check the Jenkins agent connection script.
  script: ./check-connection.sh {{ agent_name }} {{ agent_secret }}

- name: Setup a chrontab entry to run the agent script every 5th minute.
  ansible.builtin.cron:
    name: "Run slave script"
    minute: "*/5"
    job: "$HOME/jenkins-slave.sh {{ agent_name }} {{ agent_secret }}"

# Tidy up the evironment.

- name: Remove user from sudoers on new macs.
  shell: /Applications/Privileges.app/Contents/Resources/PrivilegesCLI --remove
  ignore_errors: true  # Not all the macs have these, so don't panic if it fails.
