#!/bin/bash


# retrieve semantic version of latest tag for almalinux
read -r semver_tag <<< $(../utils/equate_tag_semver "library/almalinux:latest")
test -n ${semver_tag} || exit 1

BUILT_KIT=1 docker build \
    --build-arg SEMVER_TAG=${semver_tag} \
    --tag ghcr.io/idigs/mantid-development-alma:${semver_tag }
  .

