---
# Configure macOS settings for build nodes.

- name: Disable screensaver.
  shell: defaults write com.apple.screensaver idleTime 0

- name: Disable saved application states to avoid dialog.
  shell: defaults write org.python.python NSQuitAlwaysKeepsWindows -bool false

- name: Ensure the machine boots back up after a power failure.
  shell: systemsetup -setrestartpowerfailure on
  become: true